#!/bin/sh

targetbase="$HOME/Screenshots"
timestamp="$(date +%Hh-%Mm-%Ss-%d-%m-%Y)"
scicon="$HOME/.icons/oomox-omega_paper/apps/scalable/applets-screenshooter.svg"

scpath="$targetbase/$timestamp.png"
sc_fullscreen="scrot $scpath"
scareascreen="scrot -s $scpath"
sctimer="scrot -cd 5 $scpath"

playsound () {
    canberra-gtk-play -i screen-capture -d "take screenshot"
}

shownotif () {
    notify-send -i $scicon "Screenshot Taken" $scpath    
}

takefullscreen () {
    $sc_fullscreen
    #$sctimer
    shownotif
    playsound
    #shownotif
}

if [ ! -e $targetbase ] ; then
    mkdir -p $targetbase
fi

takefullscreen
