#!/bin/sh

targetbase="$HOME/Screenshots"
timestamp="$(date +%d-%m-%Y-%Hh-%Mm-%Ss)"
scicon="$HOME/.icons/oomox-omega_paper/apps/scalable/applets-screenshooter.svg"

scpath="$targetbase/$timestamp.png"
scfullscreen="scrot $scpath"
scareascreen="scrot -s $scpath"
sctimer="scrot -cd 5 $scpath"

playsound () {
    canberra-gtk-play -i camera-shutter -d "take screenshot"
}

shownotif () {
    notify-send -i $scicon "Screenshot Taken" $scpath    
}

takefullscreen () {
    $scfullscreen
    #$sctimer
    shownotif
    playsound
    #shownotif
}

if [ ! -e $targetbase ] ; then
    mkdir -p $targetbase
fi

takefullscreen
